picks = {
	"Matsuyama": "Jordan Ruck",
	"Mickelson": "Sophie Hudson",
	"Snedeker": "Carol Hudson",
	"Stricker": "Ben Simpson",
	"McIlroy": "Ash Bestow",
	"Donaldson": "Ollie Wilcox",
	"Rose": "Ed Dawes",
	"Leishman": "Jason Smith",
	"Mcdowell": "Andy Burton",
	"Delaet": "Chris Ruck",
	"English": "Jackie Ruck",
	"Westwood": "Doug Price",
	"Watson": "Sam Burton",
	"Day": "James England",
	"Schwartzel": "James Gibson",
	"Dustin Johnson": "Mr Gibson",
	"Mahan": "Filkrat",
	"Moore": "Kieran Roe",
	"Watney": "Jack Peacock",
	"Bradley": "Chris Wakefield",
	"Speith": "Edward Macmillan",
	"Choice": "Connor McCormack",
	"Donald": "Cameron Thornburn",
	"Haas": "Tom Appleyard",
	"Poulter": "Dan Weston",
	"Kuchar": "Sam Fowler",
	"Stenson": "Dobby",
	"Scott": "Ryan Weston",
	"Oosthuizen": "Rob Whittaker",
	"Simpson": "Johnson Kitete",
	"Dubuisson": "Tom Burrows",
	"Els": "Darren Pickering",
	"Zach Johnson": "Pete Stillwell",
	"Garcia": "Will Watson",
	"Furyck": "Rachel Robinson",
	"Walker": "Lynda Weston",
	"Dufner": "Geoff Weston",
	"Cabrera": "Andy Swindell",
	"Olesen": "The Dog",
	"Sophocleous": "Patrick Reed",
	"Woodland": "Philip Smith",
	"Every": "Phil Stevenson",
	"Fowler": "Joe Mayor",
	"Clark": "Jordan Ruck",
	"Langer": "Sophie Hudson",
	"O-Meara": "Carol Hudson",
	"Luiten": "Ben Simpson",
	"Castano": "Ash Bestow",
	"Couples": "Ollie Wilcox",
	"Molinari": "Ed Dawes",
	"Gallagher": "Jason Smith",
	"Stadler": "Andy Burton",
	"Hanson": "Chris Ruck",
	"Stallings": "Jackie Ruck",
	"Duke": "Doug Price",
	"Manasserro": "Sam Burton",
	"Crenshaw": "James England",
	"Bowditch": "James Gibson",
	"Grace": "Mr Gibson",
	"Clarke": "Filkrat",
	"Ernst": "Kieran Roe",
	"McCoy": "Jack Peacock",
	"YE Yang": "Chris Wakefield",
	"Senden": "Edward Macmillan",
	"Porteous": "Connor McCormack",
	"Chang woo": "Cameron Thornburn",
	"Lynn": "Tom Appleyard",
	"Castro": "Dan Weston",
	"Mize": "Sam Fowler",
	"Blixt": "Dobby",
	"Cink": "Ryan Weston",
	"Fitzpatrick": "Rob Whittaker",
	"Weekley": "Johnson Kitete",
	"Glover": "Tom Burrows",
	"Points": "Darren Pickering",
	"Woosnam": "Pete Stillwell",
	"Moon Bae": "Will Watson",
	"Singh": "Rachel Robinson",
	"Jaidee": "Lynda Weston",
	"Bjorn": "Geoff Weston",
	"Jiminez": "Andy Swindell",
	"Immelman": "The Dog",
	"Lyle": "Patrick Reed",
	"De Jonge": "Philip Smith",
	"Watson": "Phil Stevenson",
	"Olazabal": "Joe Mayor"

}