var url = "http://www.sportsaid.org.uk/alumni/profile/toby-tree"

picks = {
	"Matsuyama": ["Jordan Ruck", "Seed"],
	"Mickelson": ["Sophie Hudson", "Seed"],
	"Snedeker": ["Carol Hudson", "Seed"],
	"Stricker": ["Ben Simpson", "Seed"],
	"McIlroy": ["Ash Bestow", "Seed"],
	"Donaldson": ["Ollie Wilcox", "Seed"],
	"Rose": ["Ed Dawes", "Seed", "Sports Aid Athete"],
	"Leishman": ["Jason Smith", "Seed"],
	"McDowell": ["Andy Burton", "Seed"],
	"Delaet": ["Chris Ruck", "Seed"],
	"English": ["Jackie Ruck", "Seed", "Sports Aid Athlete"],
	"Westwood": ["Doug Price", "Seed"],
	"B Watson": ["Sam Burton", "Seed"],
	"Day": ["James England", "Seed"],
	"Schwartzel": ["James Gibson", "Seed"],
	"D Johnson": ["Mr Gibson", "Seed"],
	"Mahan": ["Filkrat", "Seed"],
	"Moore": ["Kieran Roe", "Seed"],
	"Watney": ["Jack Peacock", "Seed"],
	"Bradley": ["Chris Wakefield", "Seed"],
	"Spieth": ["Edward Macmillan", "Seed"],
	"Choi": ["Connor McCormack", "Seed"],
	"Donald": ["Cameron Thornburn", "Seed", "Sports Aid Athlete"],
	"Haas": ["Tom Appleyard", "Seed"],
	"Poulter": ["Dan Weston", "Seed"],
	"Kuchar": ["Sam Fowler", "Seed"],
	"Stenson": ["Dobby", "Seed"],
	"Scott": ["Ryan Weston", "Seed", "Sports Aid Athlete"],
	"Oosthuizen": ["Rob Whittaker", "Seed"],
	"Simpson": ["Johnson Kitete", "Seed"],
	"Dubuisson": ["Tom Burrows", "Seed"],
	"Els": ["Darren Pickering", "Seed"],
	"Z Johnson": ["Pete Stillwell", "Seed"],
	"Garcia": ["Will Watson", "Seed"],
	"Furyk": ["Rachel Robinson", "Seed"],
	"Walker": ["Lynda Weston", "Seed", "Sports Aid Athlete"],
	"Dufner": ["Geoff Weston", "Seed"],
	"Cabrera": ["Andy Swindell", "Seed"],
	"Thorbjorn Olesen": ["The Dog", "Seed"],
	"Reed": ["Chris Sophocleous", "Seed"],
	"Woodland": ["Philip Smith", "Seed"],
	"Every": ["Phil Stevenson", "Seed"],
	"Fowler": ["Joe Mayor", "Seed"],
	"Clark": ["Jordan Ruck", "Wildcard"],
	"Langer": ["Sophie Hudson", "Wildcard"],
	"O'Meara": ["Carol Hudson", "Wildcard"],
	"Luiten": ["Ben Simpson", "Wildcard"],
	"Gonzalo Fernandez-Castano": ["Ash Bestow", "Wildcard"],
	"Couples": ["Ollie Wilcox", "Wildcard"],
	"F Molinari": ["Ed Dawes", "Wildcard"],
	"Gallacher": ["Jason Smith", "Wildcard"],
	"Stadler": ["Andy Burton", "Wildcard"],
	"Hanson": ["Chris Ruck", "Wildcard"],
	"Stallings": ["Jackie Ruck", "Wildcard"],
	"Duke": ["Doug Price", "Wildcard"],
	"Manassero": ["Sam Burton", "Wildcard"],
	"Crenshaw": ["James England", "Wildcard"],
	"Bowditch": ["James Gibson", "Wildcard"],
	"Grace": ["Mr Gibson", "Wildcard"],
	"Clarke": ["Filkrat", "Wildcard"],
	"Ernst": ["Kieran Roe", "Wildcard"],
	"McCoy": ["Jack Peacock", "Wildcard"],
	"YE Yang": ["Chris Wakefield", "Wildcard"],
	"Senden": ["Edward Macmillan", "Wildcard", "<a href="+url+">Sports Aid Athlete</a>"],
	"Porteous": ["Connor McCormack", "Wildcard"],
	"Lee": ["Cameron Thornburn", "Wildcard"],
	"Lynn": ["Tom Appleyard", "Wildcard"],
	"Castro": ["Dan Weston", "Wildcard"],
	"Mize": ["Sam Fowler", "Wildcard"],
	"Blixt": ["Dobby", "Wildcard"],
	"Cink": ["Ryan Weston", "Wildcard"],
	"Fitzpatrick": ["Rob Whittaker", "Wildcard"],
	"Weekley": ["Johnson Kitete", "Wildcard"],
	"Glover": ["Tom Burrows", "Wildcard"],
	"Points": ["Darren Pickering", "Wildcard"],
	"Woosnam": ["Pete Stillwell", "Wildcard"],
	"Moon Bae": ["Will Watson", "Wildcard"],
	"Singh": ["Rachel Robinson", "Wildcard"],
	"Jaidee": ["Lynda Weston", "Wildcard"],
	"Bjorn": ["Geoff Weston", "Wildcard"],
	"Jimenez": ["Andy Swindell", "Wildcard"],
	"Immelman": ["The Dog", "Wildcard"],
	"Lyle": ["Patrick Reed", "Wildcard"],
	"De Jonge": ["Philip Smith", "Wildcard"],
	"T Watson": ["Phil Stevenson", "Wildcard"],
	"Olazabal": ["Joe Mayor", "Wildcard"],

	"Hideki Matsuyama": ["Jordan Ruck", "Seed"],
	"Phil Mickelson": ["Sophie Hudson", "Seed"],
	"Brandt Snedeker": ["Carol Hudson", "Seed"],
	"Steve Stricker": ["Ben Simpson", "Seed"],
	"Rory McIlroy": ["Ash Bestow", "Seed"],
	"Jamie Donaldson": ["Ollie Wilcox", "Seed"],
	"Justin Rose": ["Ed Dawes", "Seed"],
	"Marc Leishman": ["Jason Smith", "Seed"],
	"Graeme McDowell": ["Andy Burton", "Seed"],
	"Graham Delaet": ["Chris Ruck", "Seed"],
	"Harris English": ["Jackie Ruck", "Seed"],
	"Lee Westwood": ["Doug Price", "Seed"],
	"Bubba Watson": ["Sam Burton", "Seed"],
	"Jason Day": ["James England", "Seed"],
	"Charl Schwartzel": ["James Gibson", "Seed"],
	"Dustin Johnson": ["Mr Gibson", "Seed"],
	"Hunter Mahan": ["Filkrat", "Seed"],
	"Ryan Moore": ["Kieran Roe", "Seed"],
	"Nick Watney": ["Jack Peacock", "Seed"],
	"Keegan Bradley": ["Chris Wakefield", "Seed"],
	"Jordan Spieth": ["Edward Macmillan", "Seed"],
	"Choice": ["Connor McCormack", "Seed"],
	"Luke Donald": ["Cameron Thornburn", "Seed"],
	"Bill Haas": ["Tom Appleyard", "Seed"],
	"Ian Poulter": ["Dan Weston", "Seed"],
	"Matt Kuchar": ["Sam Fowler", "Seed"],
	"Henrik Stenson": ["Dobby", "Seed"],
	"Adam Scott": ["Ryan Weston", "Seed"],
	"Louis Oosthuizen": ["Rob Whittaker", "Seed"],
	"Webb Simpson": ["Johnson Kitete", "Seed"],
	"Victor Dubuisson": ["Tom Burrows", "Seed"],
	"Ernie Els": ["Darren Pickering", "Seed"],
	"Zach Johnson": ["Pete Stillwell", "Seed"],
	"Sergio Garcia": ["Will Watson", "Seed"],
	"Jim Furyk": ["Rachel Robinson", "Seed", "Sports Aid Athlete"],
	"Jimmy Walker": ["Lynda Weston", "Seed"],
	"Jason Dufner": ["Geoff Weston", "Seed"],
	"Angel Cabrera": ["Andy Swindell", "Seed"],
	"Olesen": ["The Dog", "Seed"],
	"Patrick Reed": ["Chris Sophocleous", "Seed"],
	"Gary Woodland": ["Philip Smith", "Seed"],
	"Matt Every": ["Phil Stevenson", "Seed"],
	"Rickie Fowler": ["Joe Mayor", "Seed"],
	"Tim Clark": ["Jordan Ruck", "Wildcard"],
	"Bernhard Langer": ["Sophie Hudson", "Wildcard"],
	"Mark OMeara": ["Carol Hudson", "Wildcard"],
	"Joost Luiten": ["Ben Simpson", "Wildcard"],
	"Gonzalo Fernandez-Castano": ["Ash Bestow", "Wildcard"],
	"Fred Couples": ["Ollie Wilcox", "Wildcard"],
	"Francesco Molinari": ["Ed Dawes", "Wildcard"],
	"Stephen Gallacher": ["Jason Smith", "Wildcard"],
	"Kevin Stadler": ["Andy Burton", "Wildcard"],
	"Peter Hanson": ["Chris Ruck", "Wildcard"],
	"Scott Stallings": ["Jackie Ruck", "Wildcard"],
	"Ken Duke": ["Doug Price", "Wildcard"],
	"Matteo Manassero": ["Sam Burton", "Wildcard"],
	"Ben Crenshaw": ["James England", "Wildcard"],
	"Steven Bowditch": ["James Gibson", "Wildcard"],
	"Branden Grace": ["Mr Gibson", "Wildcard"],
	"Darren Clarke": ["Filkrat", "Wildcard"],
	"Derek Ernst": ["Kieran Roe", "Wildcard"],
	"Michael McCoy": ["Jack Peacock", "Wildcard"],
	"Y.E Yang": ["Chris Wakefield", "Wildcard"],
	"John Senden": ["Edward Macmillan", "Wildcard"],
	"Garrick Porteous": ["Connor McCormack", "Wildcard"],
	"Chang Woo Lee": ["Cameron Thornburn", "Wildcard"],
	"David Lynn": ["Tom Appleyard", "Wildcard"],
	"Roberto Castro": ["Dan Weston", "Wildcard"],
	"Larry Mize": ["Sam Fowler", "Wildcard"],
	"Jonas Blixt": ["Dobby", "Wildcard"],
	"Stewart Cink": ["Ryan Weston", "Wildcard"],
	"Matthew Fitzpatrick": ["Rob Whittaker", "Wildcard"],
	"Boo Weekley": ["Johnson Kitete", "Wildcard"],
	"Lucas Glover": ["Tom Burrows", "Wildcard"],
	"D.A. Points": ["Darren Pickering", "Wildcard"],
	"Ian Woosnam": ["Pete Stillwell", "Wildcard"],
	"Sang-Moon Bae": ["Will Watson", "Wildcard"],
	"Vijay Singh": ["Rachel Robinson", "Wildcard"],
	"Thongchai Jaidee": ["Lynda Weston", "Wildcard"],
	"Thomas Bjorn": ["Geoff Weston", "Wildcard"],
	"Miguel Angel Jimenez": ["Andy Swindell", "Wildcard"],
	"Trevor Immelman": ["The Dog", "Wildcard"],
	"Sandy Lyle": ["Patrick Reed", "Wildcard"],
	"Brendon De Jonge": ["Philip Smith", "Wildcard"],
	"Tom Watson": ["Phil Stevenson", "Wildcard"],
	"Jose Maria Olazabal": ["Joe Mayor", "Wildcard"]

}