picks = {
	"Matsuyama": ["Jordan Ruck", "Seed"],
	"Mickelson": ["Sophie Hudson", "Seed"],
	"Snedeker": ["Carol Hudson", "Seed"],
	"Stricker": ["Ben Simpson", "Seed"],
	"McIlroy": ["Ash Bestow", "Seed"],
	"Donaldson": ["Ollie Wilcox", "Seed"],
	"Rose": ["Ed Dawes", "Seed"],
	"Leishman": ["Jason Smith", "Seed"],
	"Mcdowell": ["Andy Burton", "Seed"],
	"Delaet": ["Chris Ruck", "Seed"],
	"English": ["Jackie Ruck", "Seed"],
	"Westwood": ["Doug Price", "Seed"],
	"Watson": ["Sam Burton", "Seed"],
	"Day": ["James England", "Seed"],
	"Schwartzel": ["James Gibson", "Seed"],
	"Dustin Johnson": ["Mr Gibson", "Seed"],
	"Mahan": ["Filkrat", "Seed"],
	"Moore": ["Kieran Roe", "Seed"],
	"Watney": ["Jack Peacock", "Seed"],
	"Bradley": ["Chris Wakefield", "Seed"],
	"Speith": ["Edward Macmillan", "Seed"],
	"Choice": ["Connor McCormack", "Seed"],
	"Donald": ["Cameron Thornburn", "Seed"],
	"Haas": ["Tom Appleyard", "Seed"],
	"Poulter": ["Dan Weston", "Seed"],
	"Kuchar": ["Sam Fowler", "Seed"],
	"Stenson": ["Dobby", "Seed"],
	"Scott": ["Ryan Weston", "Seed"],
	"Oosthuizen": ["Rob Whittaker", "Seed"],
	"Simpson": ["Johnson Kitete", "Seed"],
	"Dubuisson": ["Tom Burrows", "Seed"],
	"Els": ["Darren Pickering", "Seed"],
	"Zach Johnson": ["Pete Stillwell", "Seed"],
	"Garcia": ["Will Watson", "Seed"],
	"Furyck": ["Rachel Robinson", "Seed"],
	"Walker": ["Lynda Weston", "Seed"],
	"Dufner": ["Geoff Weston", "Seed"],
	"Cabrera": ["Andy Swindell", "Seed"],
	"Olesen": ["The Dog", "Seed"],
	"Sophocleous": ["Patrick Reed", "Seed"],
	"Woodland": ["Philip Smith", "Seed"],
	"Every": ["Phil Stevenson", "Seed"],
	"Fowler": ["Joe Mayor", "Seed"],
	"Clark": ["Jordan Ruck", "Wildcard"],
	"Langer": ["Sophie Hudson", "Wildcard"],
	"O-Meara": ["Carol Hudson", "Wildcard"],
	"Luiten": ["Ben Simpson", "Wildcard"],
	"Castano": ["Ash Bestow", "Wildcard"],
	"Couples": ["Ollie Wilcox", "Wildcard"],
	"Molinari": ["Ed Dawes", "Wildcard"],
	"Gallagher": ["Jason Smith", "Wildcard"],
	"Stadler": ["Andy Burton", "Wildcard"],
	"Hanson": ["Chris Ruck", "Wildcard"],
	"Stallings": ["Jackie Ruck", "Wildcard"],
	"Duke": ["Doug Price", "Wildcard"],
	"Manasserro": ["Sam Burton", "Wildcard"],
	"Crenshaw": ["James England", "Wildcard"],
	"Bowditch": ["James Gibson", "Wildcard"],
	"Grace": ["Mr Gibson", "Wildcard"],
	"Clarke": ["Filkrat", "Wildcard"],
	"Ernst": ["Kieran Roe", "Wildcard"],
	"McCoy": ["Jack Peacock", "Wildcard"],
	"YE Yang": ["Chris Wakefield", "Wildcard"],
	"Senden": ["Edward Macmillan", "Wildcard"],
	"Porteous": ["Connor McCormack", "Wildcard"],
	"Chang woo": ["Cameron Thornburn", "Wildcard"],
	"Lynn": ["Tom Appleyard", "Wildcard"],
	"Castro": ["Dan Weston", "Wildcard"],
	"Mize": ["Sam Fowler", "Wildcard"],
	"Blixt": ["Dobby", "Wildcard"],
	"Cink": ["Ryan Weston", "Wildcard"],
	"Fitzpatrick": ["Rob Whittaker", "Wildcard"],
	"Weekley": ["Johnson Kitete", "Wildcard"],
	"Glover": ["Tom Burrows", "Wildcard"],
	"Points": ["Darren Pickering", "Wildcard"],
	"Woosnam": ["Pete Stillwell", "Wildcard"],
	"Moon Bae": ["Will Watson", "Wildcard"],
	"Singh": ["Rachel Robinson", "Wildcard"],
	"Jaidee": ["Lynda Weston", "Wildcard"],
	"Bjorn": ["Geoff Weston", "Wildcard"],
	"Jiminez": ["Andy Swindell", "Wildcard"],
	"Immelman": ["The Dog", "Wildcard"],
	"Lyle": ["Patrick Reed", "Wildcard"],
	"De Jonge": ["Philip Smith", "Wildcard"],
	"Watson": ["Phil Stevenson", "Wildcard"],
	"Olazabal": ["Joe Mayor", "Wildcard"]

}